=== bensonresseler/JavaXML/boeken.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://beta.ua.ac.be/boeken"
           elementFormDefault="qualified"
           xmlns="http://beta.ua.ac.be/boeken"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="boeken">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="boek" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titel" type="nietlegestringtype"/>
                            <xs:element name="beoordeling" type="beoordelingstype" />
                            <xs:element name="auteur" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="nietlegestringtype">
                                            <xs:attribute name="geslacht" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="m" />
                                                        <xs:enumeration value="v" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="jaartal" type="xs:gYear" default="2000"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="nietlegestringtype">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="beoordelingstype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="slecht"/>
            <xs:enumeration value="heel goed"/>
            <xs:enumeration value="goed" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== bensonresseler/JavaXML/boeken.xml
<?xml version="1.0" encoding="UTF-8"?>
<boeken xmlns="http://beta.ua.ac.be/boeken"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://beta.ua.ac.be/boeken boeken.xsd">
    <boek>
        <titel>The HitchHiker's guide to the Galaxy</titel>
        <beoordeling>heel goed</beoordeling>
        <auteur geslacht="m">Douglas Adams</auteur>
    </boek>
    <boek>
        <titel>Sense and sensibility</titel>
        <beoordeling>goed</beoordeling>
        <auteur geslacht="v">Jane Austin</auteur>
    </boek>
</boeken>
